services:
  homeassistant:
    build:
      context: ./homeassistant/
      dockerfile: Dockerfile
      args:
        SECRET: ${SECRET}
    container_name: homeassistant
    volumes:
      - homeassistant:/config
    restart: unless-stopped
    network_mode: host

volumes:
  homeassistant:
    name: homeassistant
